[package]
name = "rs-httpbin"
version = "0.1.0"
edition = "2021"

[dependencies]
markdown = "1.0.0-alpha.21"
serde = {version = "1", features = ["derive"]}
serde_json = "1"
tokio = {version = "~1", features = ["rt-multi-thread", "signal"]}
tracing-subscriber = {version = "0.3", default-features = false, features = ["env-filter", "json", "fmt"]}
tracing = "0.1"
mime = "0.3"
axum = {version = "0.8", features = ["http2", "tower-log", "matched-path", "ws"]}
axum-extra = {version = "0.10.0", features = ["typed-header", "erased-json", "query", "cookie"]}
axum-client-ip = "0.7.0"
base64 = "~0.22"
humantime-serde = "1"
hostname = "0.4"
tokio-stream = "0.1"
minijinja = "2"
indoc = "2"
fastrand = "2"
axum_garde = {version = "0.21", features = ["axum-extra-query"], path = "./axum_garde"}
garde = {version = "0.21", features = ["derive"]}
tower = "0.5"
tower-http = {version = "0.6", features = ["trace", "cors", "compression-full", "set-header", "request-id", "util"]}
multer = "3"
serde_urlencoded = "0.7"
uuid = {version = "1.11", features = ["v4", "serde"]}
derive_more = {version = "1.0.0", features = ["deref_mut", "deref"]}
tokio-util = "0.7"
once_cell = "1.20.2"
futures-util = "0.3.31"
socketioxide = {version = "0.15.1", features = ["extensions", "state"]}
#utoipa-axum = { version = "0.1.2", optional = true }
#utoipa = { version = "5.2.0", optional = true }
#utoipa-swagger-ui = { version = "8.0.3", features = ["axum", "vendored"], optional = true }


[dev-dependencies]
anyhow = "1"
http-body-util = "0.1"
hyper-util = {version = "0.1", features = ["client-legacy"]}
test-case = "3"
tokio-tungstenite = "^0.26"

[profile.release]
strip = true      # Automatically strip symbols from the binary.
opt-level = "s"   # Optimize for size.
lto = true
codegen-units = 1 # Reduce the number of codegen units to improve optimization.

[features]
default = []
#openapi = ["dep:utoipa", "dep:utoipa-axum"]
#openapi-swagger-ui = ["openapi", "utoipa-swagger-ui"]


[workspace]
members = [
    "axum_garde",
]
