[package]
name = "rs-httpbin"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.7.5"
comrak = { version = "0.22.0", default-features = false }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.115"
tokio = { version = "1.37.0", features = ["rt-multi-thread"] }
tracing-subscriber = { features = ["tracing", "env-filter", "tracing-log"], version = "0.3.18" }
tracing = "0.1.40"
tower-http = { version = "0.5.2", features = ["tracing", "trace"] }
