app = 'oblivious-httpbin'
primary_region = 'lax'

[env]
PORT = 3000

[build]
dockerfile = 'Dockerfile'

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = "suspend"
auto_start_machines = true
min_machines_running = 0
processes = ['app']

[http_service.concurrency]
type = 'requests'
soft_limit = 2000
hard_limit = 4000

[[http_service.checks]]
  grace_period = "5s"
	interval = "30s"
	method = "GET"
	timeout = "5s"
	path = "/get"

[[vm]]
memory = '256MB'
cpu_kind = 'shared'
cpus = 1
