name: Test

on:
  push:
  workflow_dispatch:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
#          - windows-latest
          - macOS-latest
        rust_toolchain:
#          - stable
          - nightly
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      
      - uses: moonrepo/setup-rust@v1
        with:
          channel: ${{ matrix.rust_toolchain }}
          bins: cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov test --all-features --workspace --lcov --output-path lcov.info

      - name: Build
        run: cargo build --verbose

      - name: Coveralls
        if: matrix.os == 'ubuntu-latest' && matrix.rust_toolchain == 'nightly'
        uses: coverallsapp/github-action@v2.1.0
